# Generated by Django 6.0.1 on 2026-01-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_created_at_remove_recipe_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pic',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
