# Generated by Django 6.0.1 on 2026-01-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_pic_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('antipasti', 'Antipasti'), ('primi', 'Primi'), ('secondi', 'Secondi'), ('contorni', 'Contorni'), ('dolci', 'Dolci')], max_length=20),
        ),
    ]
